import Head from "next/head";
import Footer from "../components/component.footer";
import Navbar from "../components/component.navbar";
import { Oswald } from "@next/font/google";
import { url } from "inspector";
const oswald = Oswald({ style: "normal" });
// className={oswald.className}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="flex flex-col bg-gradient-to-b from-indigo-500 via-purple-500 to-pink-500"
      style={{ backgroundImage: "/background.svg" }}
    >
      <Head>
        <title>Create T3 App!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="grow pt-10">{children}</main>
      <Footer />
    </div>
  );
}
